# Generated by Django 5.0.7 on 2024-12-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='/profile_pics/default_profile_picture.jpg', upload_to='profile_pics/'),
        ),
    ]
