# Generated by Django 5.1.4 on 2024-12-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='company',
            new_name='company_name',
        ),
        migrations.AddField(
            model_name='review',
            name='compensation',
            field=models.CharField(default='Not Specified', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='description',
            field=models.TextField(default='Not Specified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='duration',
            field=models.CharField(default='Not Specified', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='location',
            field=models.CharField(default='Not Specified', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='overall_experience',
            field=models.TextField(default='Not Specified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='skills_learned',
            field=models.TextField(default='Not Specified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='skills_required',
            field=models.TextField(default='Not Specified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='Not Specified', max_length=255),
            preserve_default=False,
        ),
    ]
