# Generated by Django 5.0.7 on 2024-12-07 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_review_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='opinion',
        ),
    ]
