# Generated by Django 5.1.4 on 2024-12-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_review_opinion'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='interview_process',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='interview_tips',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='workplace_environment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
